'use client';

import { Suspense, useEffect, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { ArrowLeft, ArrowRight, CheckCircle2, Loader2 } from 'lucide-react';
import { format } from 'date-fns';
import { BookingCalendar } from '@/components/booking/BookingCalendar';
import { BookingHeader } from '@/components/booking/BookingHeader';
import { TimeSlotPicker } from '@/components/booking/TimeSlotPicker';
import type { AvailableSlotsResponse, BookingEmployee } from '@/lib/booking';
import { fetchJson } from '@/lib/booking-api';

interface EmployeesResponse { employees: BookingEmployee[]; business: { name: string; address: string | null; slug: string }; service: { id: number; name: string; durationMin: number } }
interface Confirmation { booking: { id: number; serviceName: string; employeeName: string; date: string; time: string } }

function DateTimePageContent() {
  const router = useRouter(); const params = useSearchParams();
  const serviceId = params.get('serviceId') || ''; const employeeId = params.get('employeeId') || 'anyone'; const businessName = params.get('businessName') || '';
  const [meta, setMeta] = useState<EmployeesResponse | null>(null); const [date, setDate] = useState<Date>(); const [slots, setSlots] = useState<string[]>([]); const [selectedSlot, setSelectedSlot] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (serviceId) fetchJson<EmployeesResponse>(`/api/booking/employees?serviceId=${encodeURIComponent(serviceId)}`).then(setMeta).catch(() => setError('دریافت اطلاعات خدمت ناموفق بود.')); }, [serviceId]);
  useEffect(() => { if (!date || !serviceId) return; setLoading(true); setSelectedSlot(''); setError(''); fetchJson<AvailableSlotsResponse>(`/api/booking/available-slots?serviceId=${encodeURIComponent(serviceId)}&employeeId=${encodeURIComponent(employeeId)}&date=${format(date, 'yyyy-MM-dd')}`).then((result) => setSlots(result.slots)).catch((reason: unknown) => { setSlots([]); setError(reason instanceof Error ? reason.message : 'دریافت زمان‌های خالی ناموفق بود.'); }).finally(() => setLoading(false)); }, [date, serviceId, employeeId]);
  const backHref = `/booking/employee?serviceId=${serviceId}`;
  const confirm = async () => { if (!date || !selectedSlot) return; setLoading(true); try { const result = await fetchJson<Confirmation>('/api/booking/confirm', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ serviceId: Number(serviceId), employeeId: employeeId === 'anyone' ? 'anyone' : Number(employeeId), date: format(date, 'yyyy-MM-dd'), timeSlot: selectedSlot }) }); sessionStorage.setItem('bookingConfirmation', JSON.stringify(result.booking)); router.push('/booking/confirmation'); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'ثبت رزرو ناموفق بود.'); } finally { setLoading(false); } };
  return <main className="min-h-screen bg-[#f8f9fd]" dir="rtl"><BookingHeader currentStep={3} business={meta?.business} backHref={businessName ? `/salon/${businessName}/book?service=${serviceId}&step=1` : '/'} /><section className="flex flex-col items-center gap-6 px-4 pb-20 pt-10"><header className="flex w-full max-w-[900px] flex-col items-center gap-3"><div className="flex items-center gap-2"><h2 className="text-base font-bold text-[#1e202c]">انتخاب تاریخ و ساعت</h2><span className="flex h-7 w-7 items-center justify-center rounded-full bg-[#582bf5] text-sm font-bold text-white">۳</span></div><p className="text-center text-lg font-bold text-[#1e202c]">تاریخ و ساعت مناسب خود را انتخاب کنید</p><p className="text-center text-[13px] text-[#8d92a3]">تاریخ‌های گذشته و روزهای تعطیل قابل انتخاب نیستند</p></header><div className="grid w-full max-w-[900px] gap-5 lg:grid-cols-[1fr_1fr]"><BookingCalendar selected={date} onSelect={setDate} /><div className="rounded-2xl border border-[#e4e8f0] bg-white p-5 shadow-[0_10px_30px_#00000005]"><div className="mb-5 flex items-center justify-between border-b border-[#e4e8f0] pb-4"><div><h3 className="text-base font-bold text-[#1e202c]">زمان‌های خالی</h3><p className="mt-1 text-xs text-[#8d92a3]">{date ? format(date, 'yyyy-MM-dd') : 'ابتدا یک تاریخ انتخاب کنید'}</p></div><CheckCircle2 className="h-5 w-5 text-[#582bf5]" /></div>{!date ? <p className="py-16 text-center text-sm text-[#8d92a3]">برای مشاهده زمان‌ها، یک روز را انتخاب کنید.</p> : loading ? <div className="flex justify-center py-16"><Loader2 className="h-7 w-7 animate-spin text-[#582bf5]" /></div> : error ? <p className="py-16 text-center text-sm text-rose-500">{error}</p> : slots.length === 0 ? <p className="py-16 text-center text-sm text-[#8d92a3]">برای این تاریخ زمان خالی وجود ندارد.</p> : <TimeSlotPicker slots={slots} selected={selectedSlot} onSelect={setSelectedSlot} />}</div></div><div className="flex w-full max-w-[900px] items-center justify-between"><button type="button" onClick={() => router.push(backHref)} className="flex items-center gap-2 rounded-xl border border-[#582bf5] bg-white px-6 py-3 text-sm text-[#582bf5]"><ArrowRight className="h-4 w-4" /> مرحله قبل</button><div className="hidden text-center sm:block"><p className="text-[13px] text-[#582bf5]">خدمت انتخاب‌شده: {meta?.service.name || '...'}</p><p className="text-sm font-bold text-[#1e202c]">{selectedSlot ? `ساعت انتخاب‌شده: ${selectedSlot}` : 'یک ساعت انتخاب کنید'}</p></div><button type="button" disabled={!date || !selectedSlot || loading} onClick={confirm} className="flex items-center gap-2 rounded-xl bg-[#582bf5] px-9 py-3 text-sm text-white transition-colors hover:bg-[#4822cf] disabled:cursor-not-allowed disabled:opacity-40">مرحله بعد <ArrowLeft className="h-4 w-4" /></button></div></section></main>;
}

export default function DateTimePage() { return <Suspense fallback={<div className="flex min-h-screen items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-[#582bf5]" /></div>}><DateTimePageContent /></Suspense>; }
